-- Rummy Multiplayer Schema

-- Use UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles
-- 1. Profiles
CREATE TABLE IF NOT EXISTS rummy_profiles (
  id VARCHAR(255) PRIMARY KEY, -- Google sub
  display_name VARCHAR(255),
  avatar_url TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 2. Tables
CREATE TABLE IF NOT EXISTS rummy_tables (
  id UUID PRIMARY KEY, -- Generated by JS
  host_user_id VARCHAR(255) NOT NULL,
  code VARCHAR(10) UNIQUE, -- 6 char code
  status VARCHAR(20) DEFAULT 'waiting', -- waiting, playing, finished
  max_players INT DEFAULT 6,
  disqualify_score INT DEFAULT 200,
  wild_joker_mode VARCHAR(20) DEFAULT 'open_joker', -- open_joker, closed_joker, no_joker
  -- Loser deadwood when someone else wins with a valid declare:
  -- auto_optimal = valid submitted meld slots score 0; invalid slots pay; unplaced cards get greedy auto-melds then pay remainder.
  -- submit_or_full = same slot rules; unplaced cards pay full face value (no auto-melds). No snapshot = full hand pays.
  loser_deadwood_mode VARCHAR(32) DEFAULT 'auto_optimal',
  ace_value INT DEFAULT 10,
  face_card_mode VARCHAR(16) DEFAULT 'ten', -- ten = J/Q/K => 10, rank = J/Q/K => 11/12/13
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 3. Table Players
CREATE TABLE IF NOT EXISTS rummy_table_players (
  table_id UUID REFERENCES rummy_tables(id) ON DELETE CASCADE,
  user_id VARCHAR(255) NOT NULL,
  seat INT,
  display_name VARCHAR(255),
  is_spectator BOOLEAN DEFAULT false,
  spectator_allowed JSONB, -- List of user_ids allowed to spectate this player
  total_points INT DEFAULT 0,
  disqualified BOOLEAN DEFAULT false,
  eliminated_at TIMESTAMP,
  joined_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (table_id, user_id)
);

-- 4. Rounds
CREATE TABLE IF NOT EXISTS rummy_rounds (
  id UUID PRIMARY KEY, -- Generated by JS
  table_id UUID REFERENCES rummy_tables(id) ON DELETE CASCADE,
  number INT NOT NULL,
  wild_joker_rank VARCHAR(5),
  printed_joker BOOLEAN DEFAULT false,
  stock JSONB,   -- Array of cards
  discard JSONB, -- Array of cards
  hands JSONB,   -- Map of user_id -> Array of cards
  active_user_id VARCHAR(255),
  game_mode VARCHAR(20),
  ace_value INT,
  face_card_mode VARCHAR(16) DEFAULT 'ten',
  winner_user_id VARCHAR(255),
  scores JSONB,  -- Map user_id -> score for this round
  declarations JSONB, -- Map user_id -> declaration details
  players_with_first_sequence JSONB, -- List of users who revealed/locked pure sequence
  meld_snapshots JSONB DEFAULT '{}'::jsonb, -- user_id -> { meld1..meld4, leftover } for loser scoring modes
  points_accumulated BOOLEAN DEFAULT false, -- If scores added to table_players
  finished_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 5. Spectate Permissions
CREATE TABLE IF NOT EXISTS spectate_permissions (
  table_id UUID REFERENCES rummy_tables(id) ON DELETE CASCADE,
  spectator_id VARCHAR(255),
  player_id VARCHAR(255),
  admin_approved BOOLEAN DEFAULT false,
  granted BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (table_id, spectator_id, player_id)
);

ALTER TABLE spectate_permissions
ADD COLUMN IF NOT EXISTS admin_approved BOOLEAN DEFAULT false;

ALTER TABLE rummy_tables
ADD COLUMN IF NOT EXISTS loser_deadwood_mode VARCHAR(32) DEFAULT 'auto_optimal';

ALTER TABLE rummy_tables
ADD COLUMN IF NOT EXISTS face_card_mode VARCHAR(16) DEFAULT 'ten';

ALTER TABLE rummy_rounds
ADD COLUMN IF NOT EXISTS meld_snapshots JSONB DEFAULT '{}'::jsonb;

ALTER TABLE rummy_rounds
ADD COLUMN IF NOT EXISTS face_card_mode VARCHAR(16) DEFAULT 'ten';

-- 6. Chat Messages
CREATE TABLE IF NOT EXISTS chat_messages (
  id SERIAL PRIMARY KEY,
  table_id UUID REFERENCES rummy_tables(id) ON DELETE CASCADE,
  user_id VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  is_private BOOLEAN DEFAULT false,
  recipient_id VARCHAR(255),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance

CREATE INDEX IF NOT EXISTS idx_rummy_tables_code ON rummy_tables(code);
CREATE INDEX IF NOT EXISTS idx_rummy_rounds_table_id ON rummy_rounds(table_id);
